### ISSUE TITLE
template folder

### ISSUE THREAD

**Issue by aladinko** [nebulabroadcast/nebula-setup#1]
Hello, I following this project some time. It looks great. I do not know, if I'm wrong, but I have a problem installing it:

`/opt/nebula-setup# python setup.py 
INFO        Installing site settings
INFO        Installing storages
INFO        Installing channels
INFO        Installing services
INFO        Installing actions
Traceback (most recent call last):
  File "setup.py", line 241, in <module>
    install_actions()
  File "setup.py", line 147, in install_actions
    settings = open(settings_path).read()
IOError: [Errno 2] No such file or directory: 'template/actions/proxy.xml'`

There is no folder template/actions/*.xml

**Comment by martastain** [comment]
Hello,
thanks for reporting. I am working on an installation guide so please stay tuned.

**Comment by martastain** [comment]
Setup scripts should be fixed by now.
