### ISSUE TITLE
Hi nebula team

### ISSUE THREAD

**Issue by burakguder** [nebulabroadcast/nebula-setup#2]
getting this error during setup. how can I fix this problem ?

INFO        Installing site settings
INFO        Installing storages
INFO        Installing channels
INFO        Installing services
INFO        Installing actions
INFO        Installing asset folders
INFO        Installing metadata set
Traceback (most recent call last):
  File "setup.py", line 238, in <module>
    install_meta_types()
  File "setup.py", line 202, in install_meta_types
    [key]
  File "setup.py", line 58, in query
    self.cur.execute(query, *args)
psycopg2.ProgrammingError: syntax error at or near "NOT"
LINE 1: CREATE INDEX IF NOT EXISTS idx_id_asset ON assets((meta->>'i...

**Comment by martastain** [comment]
As we discussed on Facebook. You are using Ubuntu 14.04 with PostgreSQL 9.4, which we cannot support. Please consider upgrading your OS wherever you using it since this version is very outdated (Ubuntu 14.04 reached its end of life this April).
