### ISSUE TITLE
nginx and mseg_publish error

### ISSUE THREAD

**Issue by sfahadshahzad** [nebulabroadcast/nebula-setup#3]
Hi @martastain 

I am getting error mseg_publish while running ./nebula.py mseg service unable to send mseg to relay.

have checked the nginx service is not loaded just after running make install nebula. 
nginx and nebula is running on same machine.

![Nginx server error](https://user-images.githubusercontent.com/1608007/69727559-9bf20800-1144-11ea-84ab-08ee716233d7.PNG)

![meg_publish](https://user-images.githubusercontent.com/1608007/69730386-c5616280-1149-11ea-8bab-5d2153e67c9d.PNG)

Regards,

Fahad

**Comment by martastain** [comment]
The current nginx installer does not build nginx with push-stream module by default (we're switching to nchan). You can either build nginx using `./install.nginx.sh --with-push-stream` or change the configuration file to use nchan:

```
    location /msg_publish {
        access_log              off;
        nchan_publisher;
        nchan_channel_id                $arg_id;
        nchan_message_buffer_length     50;
        nchan_message_timeout           10s;

        set $push_stream_channel_id     $arg_id;
    }
```

```
    location ~ /ws/(.*) {
        nchan_subscriber        websocket;
        nchan_channel_id        $1;

        add_header              Access-Control-Allow-Headers    'origin, content-type, accept, user-agent, referer' always;
        add_header              Access-Control-Allow-Origin     '*';
    }
```

I'll fix this in the README
