### ISSUE TITLE
Error in readme

### ISSUE THREAD

**Issue by MonsieurPoutounours** [nebulabroadcast/nebula-setup#4]
Hi, 

There is a little link error in readme file, in :

`Use install.nginx.sh and`

The link points to a ffmepg installer script, not nginx one.

Regards.

**Comment by martastain** [comment]
Fixed. Since there are probably many problems in this readme and I'll appreciate any comments from your point of view, can you please use @immstudios / nebula-setup repository, which is our development branch for reporting issues? Thanks!
