### ISSUE TITLE
Install.nginx.sh has an error

### ISSUE THREAD

**Issue by jengajenga** [nebulabroadcast/nebula-setup#7]
Hi team,

I'v been trying to set up nginx via the installer. I keep getting this error.

![nginx error](https://user-images.githubusercontent.com/65451390/111900666-edfb2300-8a44-11eb-9677-687e4e5a7aaa.PNG)

This is after I hashed out a line that was giving me a similar error - "cannot cp: nginx/nginx.conf" - because I thought it was the problem

![nginx error - hash](https://user-images.githubusercontent.com/65451390/111900711-2bf84700-8a45-11eb-8cce-7f3b1afcad2d.PNG)

What am I doing wrong? I'm running it as root as required.

**Comment by martastain** [comment]
Hello,
you need to clone the whole `installers` repository. the file which causes your error is in the `nginx` subdirectory of the repository.
